/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: axVArpcqgHCPMKB2yUGsW3
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsaTl61Gk1GKw5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: aTL61Gk1GKw5/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsaTl61Gk1GKw5
});
