/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZ8YLJfMu4Bkb27adUM6r5
// Component: 7KH7btHTInKZ
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  hasVariant,
  renderPlasmicSlot,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { BaseTextField } from "@plasmicpkgs/react-aria/skinny/registerTextField";
import Label2 from "../../Label2"; // plasmic-import: 1E9avwzW8d2p/component
import TextInput2 from "../../TextInput2"; // plasmic-import: WhTwdYVd3Yps/component
import TextAreaInput2 from "../../TextAreaInput2"; // plasmic-import: jvhZfPwC9czw/component
import Description2 from "../../Description2"; // plasmic-import: pWVYAykjFrqd/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectcss
import sty from "./PlasmicTextField2.module.css"; // plasmic-import: 7KH7btHTInKZ/css
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: XjeU4vgBHumA/icon

createPlasmicElementProxy;

export const PlasmicTextField2__VariantProps = new Array(
  "multiLine",
  "iconStart",
  "iconEnd"
);

export const PlasmicTextField2__ArgProps = new Array(
  "value",
  "placeholder",
  "showLabel",
  "showDescription",
  "disabled",
  "readOnly",
  "autoFocus",
  "type",
  "inputMode",
  "autoComplete",
  "ariaLabel",
  "onChange",
  "label",
  "start",
  "end",
  "description"
);

const $$ = {};

function PlasmicTextField2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          showLabel: true,
          showDescription: false,
          readOnly: false,
          autoFocus: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "ariaTextField.value",
        type: "writable",
        variableType: "text",
        valueProp: "value",
        onChangeProp: "onChange"
      },
      {
        path: "multiLine",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.multiLine
      },
      {
        path: "iconStart",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.iconStart
      },
      {
        path: "iconEnd",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.iconEnd
      },
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textAreaInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  const [$ccVariants, setDollarCcVariants] = React.useState({
    disabled: false,
    readonly: false
  });
  const updateVariant = React.useCallback(changes => {
    setDollarCcVariants(prev => {
      if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
        return prev;
      }
      return { ...prev, ...changes };
    });
  }, []);
  return (
    <BaseTextField
      data-plasmic-name={"ariaTextField"}
      data-plasmic-override={overrides.ariaTextField}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      autoComplete={args.autoComplete}
      autoFocus={args.autoFocus}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.ariaTextField,
        {
          [sty.ariaTextFieldiconEnd]: hasVariant($state, "iconEnd", "iconEnd"),
          [sty.ariaTextFieldiconStart]: hasVariant(
            $state,
            "iconStart",
            "iconStart"
          ),
          [sty.ariaTextFieldiconStart_iconEnd]:
            hasVariant($state, "iconStart", "iconStart") &&
            hasVariant($state, "iconEnd", "iconEnd"),
          [sty.ariaTextFieldmultiLine]: hasVariant(
            $state,
            "multiLine",
            "multiLine"
          )
        }
      )}
      inputMode={args.inputMode}
      isDisabled={args.disabled}
      isReadOnly={args.readOnly}
      onChange={async (...eventArgs) => {
        generateStateOnChangeProp($state, ["ariaTextField", "value"]).apply(
          null,
          eventArgs
        );
      }}
      plasmicUpdateVariant={updateVariant}
      type={args.type}
      value={generateStateValueProp($state, ["ariaTextField", "value"])}
    >
      {$props.showLabel ? (
        <Label2
          data-plasmic-name={"label2"}
          data-plasmic-override={overrides.label2}
          className={classNames("__wab_instance", sty.label2, {
            [sty.label2multiLine]: hasVariant($state, "multiLine", "multiLine")
          })}
        >
          {renderPlasmicSlot({
            defaultContents: "Label",
            value: args.label
          })}
        </Label2>
      ) : null}
      <div
        className={classNames(projectcss.all, sty.freeBox__k4BbS, {
          [sty.freeBoxiconEnd__k4BbSlju27]: hasVariant(
            $state,
            "iconEnd",
            "iconEnd"
          ),
          [sty.freeBoxiconStart__k4BbSQvGm6]: hasVariant(
            $state,
            "iconStart",
            "iconStart"
          ),
          [sty.freeBoxmultiLine__k4BbSq9ZdJ]: hasVariant(
            $state,
            "multiLine",
            "multiLine"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__s8Rlt, {
            [sty.freeBoxiconStart__s8RltQvGm6]: hasVariant(
              $state,
              "iconStart",
              "iconStart"
            ),
            [sty.freeBoxmultiLine__s8RltQ9ZdJ]: hasVariant(
              $state,
              "multiLine",
              "multiLine"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <CircleIcon
                className={classNames(projectcss.all, sty.svg___5TaIk)}
                role={"img"}
              />
            ),

            value: args.start,
            className: classNames(sty.slotTargetStart, {
              [sty.slotTargetStarticonStart]: hasVariant(
                $state,
                "iconStart",
                "iconStart"
              )
            })
          })}
        </div>
        {(hasVariant($state, "multiLine", "multiLine") ? false : true) ? (
          <TextInput2
            data-plasmic-name={"textInput"}
            data-plasmic-override={overrides.textInput}
            disabled={$ccVariants["disabled"] ? true : undefined}
            onChange={async (...eventArgs) => {
              generateStateOnChangeProp($state, ["textInput", "value"]).apply(
                null,
                eventArgs
              );
              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            padded={
              hasVariant($state, "iconStart", "iconStart") &&
              hasVariant($state, "iconEnd", "iconEnd")
                ? ["right", "left"]
                : hasVariant($state, "iconEnd", "iconEnd")
                  ? ["right"]
                  : hasVariant($state, "iconStart", "iconStart")
                    ? ["left"]
                    : undefined
            }
            placeholder={args.placeholder}
            value={generateStateValueProp($state, ["textInput", "value"])}
          />
        ) : null}
        {(hasVariant($state, "multiLine", "multiLine") ? true : false) ? (
          <TextAreaInput2
            data-plasmic-name={"textAreaInput"}
            data-plasmic-override={overrides.textAreaInput}
            className={classNames("__wab_instance", {
              [sty.textAreaInputmultiLine]: hasVariant(
                $state,
                "multiLine",
                "multiLine"
              )
            })}
            onChange={async (...eventArgs) => {
              generateStateOnChangeProp($state, [
                "textAreaInput",
                "value"
              ]).apply(null, eventArgs);
              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            padded={
              hasVariant($state, "iconStart", "iconStart") &&
              hasVariant($state, "iconEnd", "iconEnd")
                ? ["right", "left"]
                : hasVariant($state, "iconEnd", "iconEnd")
                  ? ["right"]
                  : hasVariant($state, "iconStart", "iconStart")
                    ? ["left"]
                    : undefined
            }
            placeholder={args.placeholder}
            value={generateStateValueProp($state, ["textAreaInput", "value"])}
          />
        ) : null}
        <div
          className={classNames(projectcss.all, sty.freeBox__rJxeS, {
            [sty.freeBoxiconEnd__rJxeSlju27]: hasVariant(
              $state,
              "iconEnd",
              "iconEnd"
            ),
            [sty.freeBoxiconStart__rJxeSQvGm6]: hasVariant(
              $state,
              "iconStart",
              "iconStart"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <CircleIcon
                className={classNames(projectcss.all, sty.svg___5Kj30)}
                role={"img"}
              />
            ),

            value: args.end,
            className: classNames(sty.slotTargetEnd)
          })}
        </div>
      </div>
      {$props.showDescription ? (
        <Description2
          data-plasmic-name={"description2"}
          data-plasmic-override={overrides.description2}
          className={classNames("__wab_instance", sty.description2)}
        >
          {renderPlasmicSlot({
            defaultContents: "Description...",
            value: args.description
          })}
        </Description2>
      ) : null}
    </BaseTextField>
  );
}

const PlasmicDescendants = {
  ariaTextField: [
    "ariaTextField",
    "label2",
    "textInput",
    "textAreaInput",
    "description2"
  ],

  label2: ["label2"],
  textInput: ["textInput"],
  textAreaInput: ["textAreaInput"],
  description2: ["description2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTextField2__ArgProps,
          internalVariantPropNames: PlasmicTextField2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTextField2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaTextField") {
    func.displayName = "PlasmicTextField2";
  } else {
    func.displayName = `PlasmicTextField2.${nodeName}`;
  }
  return func;
}

export const PlasmicTextField2 = Object.assign(
  // Top-level PlasmicTextField2 renders the root element
  makeNodeComponent("ariaTextField"),
  {
    // Helper components rendering sub-elements
    label2: makeNodeComponent("label2"),
    textInput: makeNodeComponent("textInput"),
    textAreaInput: makeNodeComponent("textAreaInput"),
    description2: makeNodeComponent("description2"),
    // Metadata about props expected for PlasmicTextField2
    internalVariantProps: PlasmicTextField2__VariantProps,
    internalArgProps: PlasmicTextField2__ArgProps
  }
);

export default PlasmicTextField2;
/* prettier-ignore-end */
