/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZ8YLJfMu4Bkb27adUM6r5
// Component: LjSN_No2rfGJ
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { BaseSection } from "@plasmicpkgs/react-aria/skinny/registerSection";
import MenuItem from "../../MenuItem"; // plasmic-import: ccoae2P36xf_/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectcss
import sty from "./PlasmicMenuSection.module.css"; // plasmic-import: LjSN_No2rfGJ/css

createPlasmicElementProxy;

export const PlasmicMenuSection__VariantProps = new Array();

export const PlasmicMenuSection__ArgProps = new Array("header", "items");

const $$ = {};

function PlasmicMenuSection__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <BaseSection
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      header={
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          {renderPlasmicSlot({
            defaultContents: "Section Header",
            value: args.header,
            className: classNames(sty.slotTargetHeader)
          })}
        </div>
      }
      items={renderPlasmicSlot({
        defaultContents: (
          <React.Fragment>
            <MenuItem label={"Section Item 1"} value={"section-item-1"} />
            <MenuItem label={"Section Item 2"} value={"section-item-2"} />
            <MenuItem label={"Section Item 3"} value={"section-item-3"} />
          </React.Fragment>
        ),

        value: args.items
      })}
    />
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMenuSection__ArgProps,
          internalVariantPropNames: PlasmicMenuSection__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMenuSection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuSection";
  } else {
    func.displayName = `PlasmicMenuSection.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuSection = Object.assign(
  // Top-level PlasmicMenuSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicMenuSection
    internalVariantProps: PlasmicMenuSection__VariantProps,
    internalArgProps: PlasmicMenuSection__ArgProps
  }
);

export default PlasmicMenuSection;
/* prettier-ignore-end */
