/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZ8YLJfMu4Bkb27adUM6r5
// Component: QycF2xGnZFTn
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  renderPlasmicSlot,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { BaseCheckbox } from "@plasmicpkgs/react-aria/skinny/registerCheckbox";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectcss
import sty from "./PlasmicCheckbox2.module.css"; // plasmic-import: QycF2xGnZFTn/css
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: LedafQG9qlFJ/icon
import MinusIcon from "./icons/PlasmicIcon__Minus"; // plasmic-import: Iucxl9Bfnjdw/icon

createPlasmicElementProxy;

export const PlasmicCheckbox2__VariantProps = new Array();

export const PlasmicCheckbox2__ArgProps = new Array(
  "value",
  "autoFocus",
  "disabled",
  "ariaLabel",
  "isSelected",
  "onChange",
  "label"
);

const $$ = {};

function PlasmicCheckbox2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          autoFocus: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "ariaCheckbox.isSelected",
        type: "writable",
        variableType: "boolean",
        valueProp: "isSelected",
        onChangeProp: "onChange"
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  const [$ccVariants, setDollarCcVariants] = React.useState({
    hovered: false,
    pressed: false,
    focused: false,
    focusVisible: false,
    indeterminate: false,
    disabled: false,
    selected: false,
    readonly: false
  });
  const updateVariant = React.useCallback(changes => {
    setDollarCcVariants(prev => {
      if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
        return prev;
      }
      return { ...prev, ...changes };
    });
  }, []);
  return (
    <BaseCheckbox
      data-plasmic-name={"ariaCheckbox"}
      data-plasmic-override={overrides.ariaCheckbox}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      autoFocus={args.autoFocus}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.ariaCheckbox
      )}
      defaultSelected={false}
      isDisabled={args.disabled}
      isIndeterminate={$ccVariants["indeterminate"] ? true : undefined}
      isSelected={generateStateValueProp($state, [
        "ariaCheckbox",
        "isSelected"
      ])}
      onChange={async (...eventArgs) => {
        generateStateOnChangeProp($state, ["ariaCheckbox", "isSelected"]).apply(
          null,
          eventArgs
        );
      }}
      plasmicUpdateVariant={updateVariant}
      value={args.value}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(
          $ccVariants["selected"] && $ccVariants["indeterminate"]
            ? false
            : $ccVariants["selected"]
              ? true
              : false
        ) ? (
          <CheckIcon
            className={classNames(projectcss.all, sty.svg__oul7S)}
            role={"img"}
          />
        ) : null}
        {($ccVariants["indeterminate"] ? true : false) ? (
          <MinusIcon
            className={classNames(projectcss.all, sty.svg__j9Id6)}
            role={"img"}
          />
        ) : null}
      </div>
      {renderPlasmicSlot({
        defaultContents: "Option",
        value: args.label
      })}
    </BaseCheckbox>
  );
}

const PlasmicDescendants = {
  ariaCheckbox: ["ariaCheckbox", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCheckbox2__ArgProps,
          internalVariantPropNames: PlasmicCheckbox2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCheckbox2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaCheckbox") {
    func.displayName = "PlasmicCheckbox2";
  } else {
    func.displayName = `PlasmicCheckbox2.${nodeName}`;
  }
  return func;
}

export const PlasmicCheckbox2 = Object.assign(
  // Top-level PlasmicCheckbox2 renders the root element
  makeNodeComponent("ariaCheckbox"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicCheckbox2
    internalVariantProps: PlasmicCheckbox2__VariantProps,
    internalArgProps: PlasmicCheckbox2__ArgProps
  }
);

export default PlasmicCheckbox2;
/* prettier-ignore-end */
