/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZ8YLJfMu4Bkb27adUM6r5
// Component: N2EmXWwtxdPX
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectcss
import sty from "./PlasmicSiteHeader.module.css"; // plasmic-import: N2EmXWwtxdPX/css
import logoOnDarkSvgWQVtk1Bauie from "./images/logoOnDarkSvg.svg"; // plasmic-import: w-qVtk1bauie/picture

createPlasmicElementProxy;

export const PlasmicSiteHeader__VariantProps = new Array();

export const PlasmicSiteHeader__ArgProps = new Array();

const $$ = {};

function PlasmicSiteHeader__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"header"}
      data-plasmic-override={overrides.header}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.header
      )}
    >
      <div
        data-plasmic-name={"wrapper"}
        data-plasmic-override={overrides.wrapper}
        className={classNames(projectcss.all, sty.wrapper)}
      >
        <PlasmicLink__
          data-plasmic-name={"homeButton"}
          data-plasmic-override={overrides.homeButton}
          className={classNames(projectcss.all, projectcss.a, sty.homeButton)}
          href={`/`}
          platform={"react"}
        >
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "32px"
                : "64px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "32px"
                : "64px"
            }
            src={{
              src: logoOnDarkSvgWQVtk1Bauie,
              fullWidth: 320,
              fullHeight: 241,
              aspectRatio: undefined
            }}
          />
        </PlasmicLink__>
        <div
          data-plasmic-name={"links"}
          data-plasmic-override={overrides.links}
          className={classNames(projectcss.all, sty.links)}
        >
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__lzZiw
            )}
            href={"./#Projects"}
            platform={"react"}
          >
            {"Projects"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__hKvHf
            )}
            href={"./#About"}
            platform={"react"}
          >
            {"About"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__gBktF
            )}
            href={"./#Skills"}
            platform={"react"}
          >
            {"Skills"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___9XW1F
            )}
            href={"./CV/ClaudioPalana_CV_EN_2026.pdf"}
            platform={"react"}
            target={"_blank"}
          >
            {"CV"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___0HvZq
            )}
            href={"./#Contact"}
            platform={"react"}
          >
            {"Contact"}
          </PlasmicLink__>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  header: ["header", "wrapper", "homeButton", "img", "links"],
  wrapper: ["wrapper", "homeButton", "img", "links"],
  homeButton: ["homeButton", "img"],
  img: ["img"],
  links: ["links"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSiteHeader__ArgProps,
          internalVariantPropNames: PlasmicSiteHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSiteHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "header") {
    func.displayName = "PlasmicSiteHeader";
  } else {
    func.displayName = `PlasmicSiteHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicSiteHeader = Object.assign(
  // Top-level PlasmicSiteHeader renders the root element
  makeNodeComponent("header"),
  {
    // Helper components rendering sub-elements
    wrapper: makeNodeComponent("wrapper"),
    homeButton: makeNodeComponent("homeButton"),
    img: makeNodeComponent("img"),
    links: makeNodeComponent("links"),
    // Metadata about props expected for PlasmicSiteHeader
    internalVariantProps: PlasmicSiteHeader__VariantProps,
    internalArgProps: PlasmicSiteHeader__ArgProps
  }
);

export default PlasmicSiteHeader;
/* prettier-ignore-end */
