/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZ8YLJfMu4Bkb27adUM6r5
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsmSpjmMAboCzh } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: MSpjmMAboCZH/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsmSpjmMAboCzh
});
