/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZ8YLJfMu4Bkb27adUM6r5
// Component: fOuqeGdfM4an
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import Tilt from "@plasmicpkgs/react-parallax-tilt";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectcss
import sty from "./PlasmicMyBeppe.module.css"; // plasmic-import: fOuqeGdfM4an/css
import myBeppeWgjwaozifOlk from "./images/myBeppe.png"; // plasmic-import: wgjwaozifOlk/picture
import plannerPersonaCc0NoxHheDkA from "./images/plannerPersona.webp"; // plasmic-import: CC0NOXHheDkA/picture
import explorerPersona8Rc9Rj0Kv6W from "./images/explorerPersona.webp"; // plasmic-import: 8-Rc9RJ0kv6W/picture
import image7NqEyIfaO9Sg1 from "./images/image7.png"; // plasmic-import: NQEyIfaO9SG1/picture
import productPagePng7QfPCgz93B from "./images/productPagePng.png"; // plasmic-import: 7QfP_cgz93_B/picture
import welcome1JpgTiZnSytmpImq from "./images/welcome1Jpg.jpeg"; // plasmic-import: TiZnSYTMPImq/picture
import welcome2Jpg9IAxkmp2BCDc from "./images/welcome2Jpg.jpeg"; // plasmic-import: 9IAxkmp2bCDc/picture
import welcome3JpgNlogTDreTb1C from "./images/welcome3Jpg.jpeg"; // plasmic-import: NlogTDreTb1C/picture
import image111TeUOnWvoDy from "./images/image11.webp"; // plasmic-import: _1teUOnWvoDY/picture

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    title: "MyBeppe - Local food, delivered with trust",
    openGraph: {
      title: "MyBeppe - Local food, delivered with trust"
    },
    twitter: {
      card: "summary",
      title: "MyBeppe - Local food, delivered with trust"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicMyBeppe__VariantProps = new Array();

export const PlasmicMyBeppe__ArgProps = new Array();

const $$ = {};

function PlasmicMyBeppe__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uGq0Y)}>
              <Reveal
                cascade={true}
                className={classNames("__wab_instance", sty.reveal__xR5Er)}
                direction={"top-right"}
                duration={2000}
                effect={"rotate"}
                triggerOnce={true}
              >
                <div className={classNames(projectcss.all, sty.freeBox__z0Ooa)}>
                  <PlasmicImg__
                    data-plasmic-name={"beppeLogo"}
                    data-plasmic-override={overrides.beppeLogo}
                    alt={""}
                    className={classNames(sty.beppeLogo)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"eager"}
                    src={{
                      src: myBeppeWgjwaozifOlk,
                      fullWidth: 1536,
                      fullHeight: 1024,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </Reveal>
              <div className={classNames(projectcss.all, sty.freeBox___08ZYq)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pJScB
                  )}
                >
                  {"MyBeppe"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__n05SI
                  )}
                >
                  {"Local food, delivered with trust."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___12UXq
                  )}
                >
                  {
                    "Zero-kilometer groceries, straight from local farmers to your home."
                  }
                </div>
                <div
                  data-plasmic-name={"details2"}
                  data-plasmic-override={overrides.details2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.details2
                  )}
                  data-project-details={"1"}
                >
                  {
                    "Buying fresh produce at a local market is never just a task.\r\nIt\u2019s a ritual made of gestures, conversations, sensory cues, and trust built over time.\r\nMyBeppe was born from a simple but ambitious question:\r\nHow can a digital product recreate the emotional richness of a farmers\u2019 market while offering the speed and clarity of modern delivery apps?\r\nThis case study explores how I approached this challenge, from research to concept, from UX strategy to a complete redesign of the interface\r."
                  }
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__n0Ljy)}>
              <Reveal
                cascade={true}
                className={classNames("__wab_instance", sty.reveal__yWjG)}
                damping={0.5}
                direction={"up"}
                effect={"fade"}
                triggerOnce={true}
              >
                <div
                  data-plasmic-name={"summary"}
                  data-plasmic-override={overrides.summary}
                  className={classNames(projectcss.all, sty.summary)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___86IGo
                    )}
                  >
                    {"YEAR"}
                  </div>
                  <div
                    data-plasmic-name={"details3"}
                    data-plasmic-override={overrides.details3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.details3
                    )}
                    data-project-details={"1"}
                  >
                    {"2023"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"summary5"}
                  data-plasmic-override={overrides.summary5}
                  className={classNames(projectcss.all, sty.summary5)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yMQz1
                    )}
                  >
                    {"Timeline"}
                  </div>
                  <div
                    data-plasmic-name={"details7"}
                    data-plasmic-override={overrides.details7}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.details7
                    )}
                    data-project-details={"1"}
                  >
                    {"Fastweb Digital Academy \u2014 4 weeks"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"summary6"}
                  data-plasmic-override={overrides.summary6}
                  className={classNames(projectcss.all, sty.summary6)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xq9El
                    )}
                  >
                    {"TEAM"}
                  </div>
                  <div
                    data-plasmic-name={"details29"}
                    data-plasmic-override={overrides.details29}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.details29
                    )}
                    data-project-details={"1"}
                  >
                    {
                      "Team Tigers (5 designers) - UX\n\nUI - Independent Work\r\n\r"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"summary2"}
                  data-plasmic-override={overrides.summary2}
                  className={classNames(projectcss.all, sty.summary2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ghhJw
                    )}
                  >
                    {"ROLE"}
                  </div>
                  <div
                    data-plasmic-name={"details4"}
                    data-plasmic-override={overrides.details4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.details4
                    )}
                    data-project-details={"1"}
                  >
                    {
                      "UX Research\nUI Design\nVisual Identity\nProduct Thinking"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"summary3"}
                  data-plasmic-override={overrides.summary3}
                  className={classNames(projectcss.all, sty.summary3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pbg6T
                    )}
                  >
                    {"TOOLS"}
                  </div>
                  <div
                    data-plasmic-name={"details5"}
                    data-plasmic-override={overrides.details5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.details5
                    )}
                    data-project-details={"1"}
                  >
                    {
                      "Figma\nAdobe Illustrator\nAdobe Photoshop\nMiro\nFigjam Boards\nComfyUI"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"summary4"}
                  data-plasmic-override={overrides.summary4}
                  className={classNames(projectcss.all, sty.summary4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kGkLp
                    )}
                  >
                    {"Achievements"}
                  </div>
                  <div
                    data-plasmic-name={"details6"}
                    data-plasmic-override={overrides.details6}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.details6
                    )}
                    data-project-details={"1"}
                  >
                    {
                      "Product Design\nVisual Identity\nUser Personas\nUser Journeys\nWireframe Design"
                    }
                  </div>
                </div>
              </Reveal>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__lAf)}>
            <nav
              data-plasmic-name={"part1Context"}
              data-plasmic-override={overrides.part1Context}
              className={classNames(projectcss.all, sty.part1Context)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fZ8E
                )}
              >
                {"Context"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__go7Dc
                )}
              >
                {"The Problem Space"}
              </div>
              <div
                data-plasmic-name={"details8"}
                data-plasmic-override={overrides.details8}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details8
                )}
                data-project-details={"1"}
              >
                {
                  "This project was developed during the Fastweb Digital Academy, as part of a team of five designers.\r\n\nThe UX research, personas, and early conceptualisation were conducted collaboratively.\r\nHowever, the entire UI redesign, visual identity, and interface system showcased in this case study were created by me alone, building on the team\u2019s foundational UX insights.\n\r\nThis dual contribution allowed me to work both as a strategic thinker and a hands\u2011on product designer, demonstrating my multipotentiality across:\n\r\n\u2022 \tUI design\r\n\u2022 \tVisual identity\r\n\u2022 \tInteraction patterns\r\n\u2022 \tProduct storytelling\n\r"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oJKdY
                )}
              >
                {"The Challenge"}
              </div>
              <div
                data-plasmic-name={"details9"}
                data-plasmic-override={overrides.details9}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details9
                )}
                data-project-details={"1"}
              >
                {
                  "Local markets thrive on trust.\r\nDigital grocery apps thrive on efficiency, but when buying fresh produce, users don\u2019t want just speed:  they want reassurance.\n\nThrough interviews and observation, we uncovered two major problems:\n\r\n\r"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dpekb
                )}
              >
                {"Problem 1 - Loss of Human Warmth"}
              </div>
              <div
                data-plasmic-name={"details30"}
                data-plasmic-override={overrides.details30}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details30
                )}
                data-project-details={"1"}
              >
                {
                  "Users miss the conversations, recommendations, and personal touch of a real vendor."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__v6Sv9
                )}
              >
                {"Problem 2 - Loss of Sensory Feedback"}
              </div>
              <div
                data-plasmic-name={"details31"}
                data-plasmic-override={overrides.details31}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details31
                )}
                data-project-details={"1"}
              >
                {
                  "Without touching or smelling produce, users feel uncertain about quality and freshness."
                }
              </div>
              <div
                data-plasmic-name={"details23"}
                data-plasmic-override={overrides.details23}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details23
                )}
                data-project-details={"1"}
              >
                {
                  "Our main objective was to translate trust, conversation, and sensory cues into a digital product, without overloading the interface. Design an experience that restores both trust and sensory reassurance."
                }
              </div>
            </nav>
          </section>
          <section className={classNames(projectcss.all, sty.section__tCwfQ)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__es6PK
              )}
            >
              {"User Research"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nyi9Z
              )}
            >
              {"Understanding the People Behind the Purchase"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qee2A
              )}
            >
              {"Our research revealed a fundamental truth:"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jjgeG
              )}
            >
              {"\r\npeople don\u2019t buy food the same way."}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rJ6Lb
              )}
            >
              {
                "Through interviews and behavioral mapping, two distinct mindsets emerged; each with different expectations, motivations, and emotional triggers."
              }
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__g6B7M)}>
              <div
                data-plasmic-name={"details10"}
                data-plasmic-override={overrides.details10}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details10
                )}
                data-project-details={"1"}
              >
                {"The Planner"}
              </div>
              <div
                data-plasmic-name={"details12"}
                data-plasmic-override={overrides.details12}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details12
                )}
                data-project-details={"1"}
              >
                {"Buys the same products regularly"}
              </div>
              <div
                data-plasmic-name={"details19"}
                data-plasmic-override={overrides.details19}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details19
                )}
                data-project-details={"1"}
              >
                {"Seeks structure, clarity, and predictability"}
              </div>
              <div
                data-plasmic-name={"details20"}
                data-plasmic-override={overrides.details20}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details20
                )}
                data-project-details={"1"}
              >
                {"Wants reassurance: freshness, shelf life, storage\r"}
              </div>
              <div
                data-plasmic-name={"details13"}
                data-plasmic-override={overrides.details13}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details13
                )}
                data-project-details={"1"}
              >
                {"Plans shopping lists and budgets in advance"}
              </div>
              <div
                data-plasmic-name={"details21"}
                data-plasmic-override={overrides.details21}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details21
                )}
                data-project-details={"1"}
              >
                {"Prefers organized layouts and efficient flows"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aSy0V
                )}
              >
                {"Wants reassurance before purchasing"}
              </div>
              <div
                data-plasmic-name={"details14"}
                data-plasmic-override={overrides.details14}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details14
                )}
                data-project-details={"1"}
              >
                {"The Explorer"}
              </div>
              <div
                data-plasmic-name={"details15"}
                data-plasmic-override={overrides.details15}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details15
                )}
                data-project-details={"1"}
              >
                {"Shops spontaneously through inspiration and curiosity"}
              </div>
              <div
                data-plasmic-name={"details16"}
                data-plasmic-override={overrides.details16}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details16
                )}
                data-project-details={"1"}
              >
                {"Treats the market as a pleasurable experience"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rEZe
                )}
              >
                {"Enjoys discovery, conversation, and recommendations"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iotLd
                )}
              >
                {"Chooses products based on inspiration and emotion"}
              </div>
              <div
                data-plasmic-name={"details11"}
                data-plasmic-override={overrides.details11}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details11
                )}
                data-project-details={"1"}
              >
                {
                  "Instead of forcing a single experience, we designed a system that embraces both mindsets without fragmenting the product."
                }
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__dTxIn)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___18HIh
              )}
            >
              {"User Journey & Mindset"}
            </div>
            <div
              data-plasmic-name={"details17"}
              data-plasmic-override={overrides.details17}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.details17
              )}
              data-project-details={"1"}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "We mapped the full journey for both personas, focusing on:\n"
                  }
                </React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__r6JLp
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li___2Dovf
                      )}
                    >
                      {"emotional states\n"}
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__r1VfP
                      )}
                    >
                      {"expectations\n"}
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__l163F
                      )}
                    >
                      {"moments of uncertainty\n"}
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__c4Cfa
                      )}
                    >
                      {"points of delight\n"}
                    </li>
                  </ul>
                }
                <React.Fragment>
                  {
                    "The design focused not only on tasks, but on how users feel before, during, and after buying."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cJcA5)}>
              <PlasmicImg__
                data-plasmic-name={"plannerPersona"}
                data-plasmic-override={overrides.plannerPersona}
                alt={""}
                className={classNames(sty.plannerPersona)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: plannerPersonaCc0NoxHheDkA,
                  fullWidth: 1558,
                  fullHeight: 988,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                data-plasmic-name={"explorerPersona"}
                data-plasmic-override={overrides.explorerPersona}
                alt={""}
                className={classNames(sty.explorerPersona)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: explorerPersona8Rc9Rj0Kv6W,
                  fullWidth: 1558,
                  fullHeight: 988,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uw3Is
              )}
            >
              {"Ideation & UX Strategy"}
            </div>
            <div
              data-plasmic-name={"details18"}
              data-plasmic-override={overrides.details18}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.details18
              )}
              data-project-details={"1"}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "Using brainwriting and the How Might We method, we identified two key opportunities:\n"
                  }
                </React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__kMEg
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__bq907
                      )}
                    >
                      {"Recreate the social interaction of a local vendor\n"}
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__pwSWx
                      )}
                    >
                      {
                        "Restore the sensory confidence users have when shopping in person\n"
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>
                  {
                    "These principles became the foundation of the product experience."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dOqAs
              )}
            >
              {"From Insights to Strategy"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kVTtB
              )}
            >
              {"Designing for Trust\r"}
            </div>
            <div
              data-plasmic-name={"details22"}
              data-plasmic-override={overrides.details22}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.details22
              )}
              data-project-details={"1"}
            >
              {
                "Across all interviews, one theme dominated: trust is the currency of local markets.\n\r\nTranslating that into a digital environment required addressing two critical gaps:"
              }
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__fytfF)}>
              <div className={classNames(projectcss.all, sty.freeBox__rDsrc)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x1V7G
                  )}
                >
                  {"A. Human Presence"}
                </div>
                <div
                  data-plasmic-name={"details24"}
                  data-plasmic-override={overrides.details24}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.details24
                  )}
                  data-project-details={"1"}
                >
                  {
                    "In physical markets, trust is built through conversation.\r\nTo recreate this, I designed \u201cBeppe\u2019s Advice\u201d, a weekly space where the farmer speaks directly to users.\r\nThis section provides:\r\n- Tips on choosing ripe produce\r\n- Seasonal insights\r\n- Short recipes\r\n- Storage guidance\nIt transforms the app from a transactional catalog into a relationship\u2011driven experience."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xF01F
                  )}
                >
                  {"B. Sensory Reassurance\r"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__v0GEf)}>
                  <div
                    data-plasmic-name={"details25"}
                    data-plasmic-override={overrides.details25}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.details25
                    )}
                    data-project-details={"1"}
                  >
                    {
                      "In a market, you touch, smell, and inspect.\r\nDigitally, you need information that compensates for the missing senses.\r\nEach product card now communicates:\r\n- Freshness level\r\n- Ripeness\r\n- Size\r\n- Shelf life\r\n- Storage tips\r\n- Suggested uses\r\nThis reduces uncertainty and increases confidence, especially for first\u2011time buyers."
                    }
                  </div>
                </div>
              </div>
              <Tilt
                className={classNames("__wab_instance", sty.tilt___0Dkg0)}
                glareBorderRadius={"2"}
                glareColor={"#FEFAE0"}
                glareEnable={true}
                glareMaxOpacity={0.4}
                glarePosition={"all"}
                glareReverse={false}
                gyroscope={true}
                perspective={1200}
                reset={true}
                tiltAngleXInitial={-90}
                tiltAngleYInitial={-30}
                tiltAxis={"y"}
                tiltMaxAngleX={10}
                tiltMaxAngleY={20}
                tiltReverse={true}
                trackOnWindow={true}
                transitionSpeed={1200}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kgC6J)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "auto"
                      : "527px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "259px"
                  }
                  loading={"lazy"}
                  src={{
                    src: image7NqEyIfaO9Sg1,
                    fullWidth: 445,
                    fullHeight: 932,
                    aspectRatio: undefined
                  }}
                />
              </Tilt>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__p19Ly)}>
            <nav
              data-plasmic-name={"projectDescription5"}
              data-plasmic-override={overrides.projectDescription5}
              className={classNames(projectcss.all, sty.projectDescription5)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gmkX
                )}
              >
                {"The Interface"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__geg9)}>
                <Tilt
                  className={classNames("__wab_instance", sty.tilt__fk8J1)}
                  glareBorderRadius={"0"}
                  glareColor={"#3D6234"}
                  glareEnable={true}
                  glareMaxOpacity={0.4}
                  glarePosition={"bottom"}
                  glareReverse={true}
                  gyroscope={true}
                  perspective={1200}
                  reset={true}
                  tiltAngleXInitial={-90}
                  tiltAngleYInitial={-30}
                  tiltAxis={"y"}
                  tiltMaxAngleX={10}
                  tiltMaxAngleY={20}
                  tiltReverse={true}
                  trackOnWindow={true}
                  transitionSpeed={1200}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___4L9Uy)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "auto"
                        : "527px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "259px"
                    }
                    loading={"lazy"}
                    src={{
                      src: productPagePng7QfPCgz93B,
                      fullWidth: 445,
                      fullHeight: 932,
                      aspectRatio: undefined
                    }}
                  />
                </Tilt>
                <div className={classNames(projectcss.all, sty.freeBox__bhtQ)}>
                  <div
                    data-plasmic-name={"details26"}
                    data-plasmic-override={overrides.details26}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.details26
                    )}
                    data-project-details={"1"}
                  >
                    {
                      "\rWhile the UX foundations were developed as a team, I redesigned the entire interface system from scratch.\r\nMy goals were to:\r\n- Create a visual identity that feels warm, natural, and trustworthy\r\n- Build a layout that supports both efficiency and exploration\r\n- Reduce cognitive load through a clear hierarchy and calm visual rhythm\r\n- Integrate storytelling without compromising usability\r\nKey UI Decisions\r\n- Soft, organic shapes to evoke a market atmosphere\r\n- A colour palette inspired by fresh produce and natural tones\r\n- Typography that balances friendliness with readability\r\n- High\u2011contrast, accessible components\r\n- Modular cards for seasonal picks, offers, and Beppe\u2019s Advice\r\n- A home screen that adapts to user behaviour"
                    }
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tjE3H
                )}
              >
                {"Critical Thinking"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__suDjA
                )}
              >
                {"Balancing Emotion and Function"}
              </div>
              <div
                data-plasmic-name={"details27"}
                data-plasmic-override={overrides.details27}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details27
                )}
                data-project-details={"1"}
              >
                {
                  "One of the most complex challenges was balancing emotional storytelling with functional clarity.\r\nToo much storytelling risks slowing down the experience.\r Too much efficiency risks losing the warmth that makes local markets special.\r\n\nMy approach:\r\n- Use storytelling in dedicated spaces (Beppe\u2019s Advice, seasonal highlights)\r\n- Keep transactional flows clean and predictable\r\n- Use micro\u2011interactions to add personality without adding friction\r\n- Prioritise information architecture to support both mindsets\n\r\nThis balance is what gives MyBeppe its identity:\r\na product that feels human without sacrificing usability.\n\nA strong example of this strong storytelling is on the welcome screen you get when launching the app the first time.\r\n"
                }
              </div>
            </nav>
            <div className={classNames(projectcss.all, sty.freeBox__x5VYr)}>
              <Tilt
                className={classNames("__wab_instance", sty.tilt__lmn3U)}
                glareBorderRadius={"2"}
                glareColor={"#3D6234"}
                glareEnable={true}
                glareMaxOpacity={0.4}
                glarePosition={"all"}
                glareReverse={false}
                gyroscope={true}
                perspective={1200}
                reset={true}
                tiltAngleXInitial={-90}
                tiltAngleYInitial={-30}
                tiltAxis={"y"}
                tiltMaxAngleX={10}
                tiltMaxAngleY={20}
                tiltReverse={true}
                trackOnWindow={false}
                transitionSpeed={1200}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__cBgvD)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "auto"
                      : "527px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "259px"
                  }
                  loading={"lazy"}
                  src={{
                    src: welcome1JpgTiZnSytmpImq,
                    fullWidth: 445,
                    fullHeight: 932,
                    aspectRatio: undefined
                  }}
                />
              </Tilt>
              <Tilt
                className={classNames("__wab_instance", sty.tilt__gTRr)}
                flipHorizontally={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? false
                    : undefined
                }
                flipVertically={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? false
                    : undefined
                }
                glareBorderRadius={"2"}
                glareColor={"#3D6234"}
                glareEnable={true}
                glareMaxOpacity={0.4}
                glarePosition={"all"}
                glareReverse={false}
                gyroscope={true}
                perspective={1200}
                reset={true}
                tiltAngleXInitial={
                  hasVariant(globalVariants, "screen", "mobileOnly") ? 90 : -90
                }
                tiltAngleYInitial={
                  hasVariant(globalVariants, "screen", "mobileOnly") ? 30 : -30
                }
                tiltAxis={"y"}
                tiltMaxAngleX={10}
                tiltMaxAngleY={20}
                tiltReverse={true}
                trackOnWindow={false}
                transitionSpeed={1200}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ndnPb)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cnS3T)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "auto"
                        : "527px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "259px"
                    }
                    loading={"lazy"}
                    src={{
                      src: welcome2Jpg9IAxkmp2BCDc,
                      fullWidth: 445,
                      fullHeight: 932,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </Tilt>
              <Tilt
                className={classNames("__wab_instance", sty.tilt__njR0U)}
                glareBorderRadius={"2"}
                glareColor={"#3D6234"}
                glareEnable={true}
                glareMaxOpacity={0.4}
                glarePosition={"all"}
                glareReverse={false}
                gyroscope={true}
                perspective={1200}
                reset={true}
                tiltAngleXInitial={-90}
                tiltAngleYInitial={-30}
                tiltAxis={"y"}
                tiltMaxAngleX={10}
                tiltMaxAngleY={20}
                tiltReverse={true}
                trackOnWindow={false}
                transitionSpeed={1200}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__q1TjV)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "auto"
                      : "527px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "259px"
                  }
                  loading={"lazy"}
                  src={{
                    src: welcome3JpgNlogTDreTb1C,
                    fullWidth: 445,
                    fullHeight: 932,
                    aspectRatio: undefined
                  }}
                />
              </Tilt>
            </div>
          </section>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__v4Sqd)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: image111TeUOnWvoDy,
              fullWidth: 2824,
              fullHeight: 1536,
              aspectRatio: undefined
            }}
          />

          <section className={classNames(projectcss.all, sty.section__uwaul)}>
            <nav
              data-plasmic-name={"projectDescription6"}
              data-plasmic-override={overrides.projectDescription6}
              className={classNames(projectcss.all, sty.projectDescription6)}
            >
              <div
                data-plasmic-name={"details28"}
                data-plasmic-override={overrides.details28}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details28
                )}
                data-project-details={"1"}
              >
                {
                  "One of the most complex challenges was balancing emotional storytelling with functional clarity.\r\nToo much storytelling risks slowing down the experience.\r\nToo much efficiency risks losing the warmth that makes local markets special.\r\nMy approach:\r\n- Use storytelling in dedicated spaces (Beppe\u2019s Advice, seasonal highlights)\r\n- Keep transactional flows clean and predictable\r\n- Use micro\u2011interactions to add personality without adding friction\r\n- Prioritize information architecture to support both mindsets\r\nThis balance is what gives MyBeppe its identity:\r\na product that feels human without sacrificing usability.\r\n"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4UyRn
                )}
              >
                {"Visual Identity "}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vfdZl
                )}
              >
                {"A Trust Signal in Itself\r"}
              </div>
              <div
                data-plasmic-name={"details33"}
                data-plasmic-override={overrides.details33}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details33
                )}
                data-project-details={"1"}
              >
                {
                  "The brand identity was designed around three core values: Trust, familiarity, and naturality\nTypography, colours, and layout work together to reduce friction and increase perceived reliability.\n\nThe interface doesn\u2019t shout, thanks to not being oversaturated with earthly colours. \nIt reassures."
                }
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__tscwM)}>
                <div
                  data-plasmic-name={"palette"}
                  data-plasmic-override={overrides.palette}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette
                  )}
                  data-project-details={"1"}
                >
                  {"#9D3C3A"}
                </div>
                <div
                  data-plasmic-name={"palette2"}
                  data-plasmic-override={overrides.palette2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette2
                  )}
                  data-project-details={"1"}
                >
                  {"#BC4749"}
                </div>
                <div
                  data-plasmic-name={"palette3"}
                  data-plasmic-override={overrides.palette3}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette3
                  )}
                  data-project-details={"1"}
                >
                  {"#DE5753"}
                </div>
                <div
                  data-plasmic-name={"palette4"}
                  data-plasmic-override={overrides.palette4}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette4
                  )}
                  data-project-details={"1"}
                >
                  {"#D07D82"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__uqHse)}>
                <div
                  data-plasmic-name={"palette5"}
                  data-plasmic-override={overrides.palette5}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette5
                  )}
                  data-project-details={"1"}
                >
                  {"#3D6234"}
                </div>
                <div
                  data-plasmic-name={"palette6"}
                  data-plasmic-override={overrides.palette6}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette6
                  )}
                  data-project-details={"1"}
                >
                  {"#6A994E"}
                </div>
                <div
                  data-plasmic-name={"palette7"}
                  data-plasmic-override={overrides.palette7}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette7
                  )}
                  data-project-details={"1"}
                >
                  {"#8ABD61"}
                </div>
                <div
                  data-plasmic-name={"palette8"}
                  data-plasmic-override={overrides.palette8}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette8
                  )}
                  data-project-details={"1"}
                >
                  {"#ACD08F"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ezfU5)}>
                <div
                  data-plasmic-name={"palette9"}
                  data-plasmic-override={overrides.palette9}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette9
                  )}
                  data-project-details={"1"}
                >
                  {"#4C3918"}
                </div>
                <div
                  data-plasmic-name={"palette10"}
                  data-plasmic-override={overrides.palette10}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette10
                  )}
                  data-project-details={"1"}
                >
                  {"#756344"}
                </div>
                <div
                  data-plasmic-name={"palette11"}
                  data-plasmic-override={overrides.palette11}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette11
                  )}
                  data-project-details={"1"}
                >
                  {"#EBDAB8"}
                </div>
                <div
                  data-plasmic-name={"palette12"}
                  data-plasmic-override={overrides.palette12}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.palette12
                  )}
                  data-project-details={"1"}
                >
                  {"#F4ECD8"}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0XoFo
                )}
              >
                {"The result"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__muZua
                )}
              >
                {"A Digital Market Experience"}
              </div>
              <div
                data-plasmic-name={"details34"}
                data-plasmic-override={overrides.details34}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.details34
                )}
                data-project-details={"1"}
              >
                {
                  "MyBeppe is more than a delivery app.\r\nIt\u2019s a digital translation of a local market, where UX, UI, and storytelling work together to build trust one interaction at a time.\n\n\r\nWhat this project demonstrates\r\n- My ability to move from research insights to strategic design decisions\r\n- My capacity to own an entire interface system end\u2011to\u2011end\r\n- My skill in blending usability, emotion, and brand identity\r\n- My multipotentiality across UX, UI, branding, and product thinking\r\n- My ability to work in a team while also delivering independent, high\u2011quality design work\r\n\r"
                }
              </div>
            </nav>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "hero",
    "beppeLogo",
    "details2",
    "summary",
    "details3",
    "summary5",
    "details7",
    "summary6",
    "details29",
    "summary2",
    "details4",
    "summary3",
    "details5",
    "summary4",
    "details6",
    "part1Context",
    "details8",
    "details9",
    "details30",
    "details31",
    "details23",
    "details10",
    "details12",
    "details19",
    "details20",
    "details13",
    "details21",
    "details14",
    "details15",
    "details16",
    "details11",
    "details17",
    "plannerPersona",
    "explorerPersona",
    "details18",
    "details22",
    "details24",
    "details25",
    "projectDescription5",
    "details26",
    "details27",
    "projectDescription6",
    "details28",
    "details33",
    "palette",
    "palette2",
    "palette3",
    "palette4",
    "palette5",
    "palette6",
    "palette7",
    "palette8",
    "palette9",
    "palette10",
    "palette11",
    "palette12",
    "details34"
  ],

  hero: [
    "hero",
    "beppeLogo",
    "details2",
    "summary",
    "details3",
    "summary5",
    "details7",
    "summary6",
    "details29",
    "summary2",
    "details4",
    "summary3",
    "details5",
    "summary4",
    "details6"
  ],

  beppeLogo: ["beppeLogo"],
  details2: ["details2"],
  summary: ["summary", "details3"],
  details3: ["details3"],
  summary5: ["summary5", "details7"],
  details7: ["details7"],
  summary6: ["summary6", "details29"],
  details29: ["details29"],
  summary2: ["summary2", "details4"],
  details4: ["details4"],
  summary3: ["summary3", "details5"],
  details5: ["details5"],
  summary4: ["summary4", "details6"],
  details6: ["details6"],
  part1Context: [
    "part1Context",
    "details8",
    "details9",
    "details30",
    "details31",
    "details23"
  ],

  details8: ["details8"],
  details9: ["details9"],
  details30: ["details30"],
  details31: ["details31"],
  details23: ["details23"],
  details10: ["details10"],
  details12: ["details12"],
  details19: ["details19"],
  details20: ["details20"],
  details13: ["details13"],
  details21: ["details21"],
  details14: ["details14"],
  details15: ["details15"],
  details16: ["details16"],
  details11: ["details11"],
  details17: ["details17"],
  plannerPersona: ["plannerPersona"],
  explorerPersona: ["explorerPersona"],
  details18: ["details18"],
  details22: ["details22"],
  details24: ["details24"],
  details25: ["details25"],
  projectDescription5: ["projectDescription5", "details26", "details27"],
  details26: ["details26"],
  details27: ["details27"],
  projectDescription6: [
    "projectDescription6",
    "details28",
    "details33",
    "palette",
    "palette2",
    "palette3",
    "palette4",
    "palette5",
    "palette6",
    "palette7",
    "palette8",
    "palette9",
    "palette10",
    "palette11",
    "palette12",
    "details34"
  ],

  details28: ["details28"],
  details33: ["details33"],
  palette: ["palette"],
  palette2: ["palette2"],
  palette3: ["palette3"],
  palette4: ["palette4"],
  palette5: ["palette5"],
  palette6: ["palette6"],
  palette7: ["palette7"],
  palette8: ["palette8"],
  palette9: ["palette9"],
  palette10: ["palette10"],
  palette11: ["palette11"],
  palette12: ["palette12"],
  details34: ["details34"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMyBeppe__ArgProps,
          internalVariantPropNames: PlasmicMyBeppe__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMyBeppe__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMyBeppe";
  } else {
    func.displayName = `PlasmicMyBeppe.${nodeName}`;
  }
  return func;
}

export const PlasmicMyBeppe = Object.assign(
  // Top-level PlasmicMyBeppe renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    hero: makeNodeComponent("hero"),
    beppeLogo: makeNodeComponent("beppeLogo"),
    details2: makeNodeComponent("details2"),
    summary: makeNodeComponent("summary"),
    details3: makeNodeComponent("details3"),
    summary5: makeNodeComponent("summary5"),
    details7: makeNodeComponent("details7"),
    summary6: makeNodeComponent("summary6"),
    details29: makeNodeComponent("details29"),
    summary2: makeNodeComponent("summary2"),
    details4: makeNodeComponent("details4"),
    summary3: makeNodeComponent("summary3"),
    details5: makeNodeComponent("details5"),
    summary4: makeNodeComponent("summary4"),
    details6: makeNodeComponent("details6"),
    part1Context: makeNodeComponent("part1Context"),
    details8: makeNodeComponent("details8"),
    details9: makeNodeComponent("details9"),
    details30: makeNodeComponent("details30"),
    details31: makeNodeComponent("details31"),
    details23: makeNodeComponent("details23"),
    details10: makeNodeComponent("details10"),
    details12: makeNodeComponent("details12"),
    details19: makeNodeComponent("details19"),
    details20: makeNodeComponent("details20"),
    details13: makeNodeComponent("details13"),
    details21: makeNodeComponent("details21"),
    details14: makeNodeComponent("details14"),
    details15: makeNodeComponent("details15"),
    details16: makeNodeComponent("details16"),
    details11: makeNodeComponent("details11"),
    details17: makeNodeComponent("details17"),
    plannerPersona: makeNodeComponent("plannerPersona"),
    explorerPersona: makeNodeComponent("explorerPersona"),
    details18: makeNodeComponent("details18"),
    details22: makeNodeComponent("details22"),
    details24: makeNodeComponent("details24"),
    details25: makeNodeComponent("details25"),
    projectDescription5: makeNodeComponent("projectDescription5"),
    details26: makeNodeComponent("details26"),
    details27: makeNodeComponent("details27"),
    projectDescription6: makeNodeComponent("projectDescription6"),
    details28: makeNodeComponent("details28"),
    details33: makeNodeComponent("details33"),
    palette: makeNodeComponent("palette"),
    palette2: makeNodeComponent("palette2"),
    palette3: makeNodeComponent("palette3"),
    palette4: makeNodeComponent("palette4"),
    palette5: makeNodeComponent("palette5"),
    palette6: makeNodeComponent("palette6"),
    palette7: makeNodeComponent("palette7"),
    palette8: makeNodeComponent("palette8"),
    palette9: makeNodeComponent("palette9"),
    palette10: makeNodeComponent("palette10"),
    palette11: makeNodeComponent("palette11"),
    palette12: makeNodeComponent("palette12"),
    details34: makeNodeComponent("details34"),
    // Metadata about props expected for PlasmicMyBeppe
    internalVariantProps: PlasmicMyBeppe__VariantProps,
    internalArgProps: PlasmicMyBeppe__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/projects/my-beppe",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicMyBeppe;
/* prettier-ignore-end */
