/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZ8YLJfMu4Bkb27adUM6r5
// Component: LYzWwMCJxMAK
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  hasVariant,
  renderPlasmicSlot,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { BaseSelect } from "@plasmicpkgs/react-aria/skinny/registerSelect";
import Label2 from "../../Label2"; // plasmic-import: 1E9avwzW8d2p/component
import { BaseButton } from "@plasmicpkgs/react-aria/skinny/registerButton";
import { BaseSelectValue } from "@plasmicpkgs/react-aria/skinny/registerSelect";
import Description2 from "../../Description2"; // plasmic-import: pWVYAykjFrqd/component
import MenuPopover2 from "../../MenuPopover2"; // plasmic-import: P4f6yKajuHQD/component
import MenuItem2 from "../../MenuItem2"; // plasmic-import: luKSQvpJebu4/component
import MenuSection2 from "../../MenuSection2"; // plasmic-import: 05hze2VuksAh/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectcss
import sty from "./PlasmicSelect2.module.css"; // plasmic-import: LYzWwMCJxMAK/css
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: JW5WVa_GgYXH/icon

createPlasmicElementProxy;

export const PlasmicSelect2__VariantProps = new Array("type");

export const PlasmicSelect2__ArgProps = new Array(
  "isOpen",
  "onOpenChange",
  "value",
  "onChange",
  "placeholder",
  "showLabel",
  "showDescription",
  "disabled",
  "ariaLabel",
  "label",
  "description",
  "items"
);

const $$ = {};

function PlasmicSelect2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          placeholder: "Select an item",
          showLabel: true,
          showDescription: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "ariaSelect.isOpen",
        type: "writable",
        variableType: "boolean",
        valueProp: "isOpen",
        onChangeProp: "onOpenChange"
      },
      {
        path: "ariaSelect.selectedValue",
        type: "writable",
        variableType: "text",
        valueProp: "value",
        onChangeProp: "onChange"
      },
      {
        path: "type",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.type
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  const [$ccVariants, setDollarCcVariants] = React.useState({
    focused: false,
    focusVisible: false,
    disabled: false
  });
  const updateVariant = React.useCallback(changes => {
    setDollarCcVariants(prev => {
      if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
        return prev;
      }
      return { ...prev, ...changes };
    });
  }, []);
  return (
    <BaseSelect
      data-plasmic-name={"ariaSelect"}
      data-plasmic-override={overrides.ariaSelect}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.ariaSelect,
        { [sty.ariaSelecttype_soft]: hasVariant($state, "type", "soft") }
      )}
      isDisabled={args.disabled}
      isOpen={generateStateValueProp($state, ["ariaSelect", "isOpen"])}
      onOpenChange={async (...eventArgs) => {
        generateStateOnChangeProp($state, ["ariaSelect", "isOpen"]).apply(
          null,
          eventArgs
        );
      }}
      onSelectionChange={async (...eventArgs) => {
        generateStateOnChangeProp($state, [
          "ariaSelect",
          "selectedValue"
        ]).apply(null, eventArgs);
      }}
      plasmicUpdateVariant={updateVariant}
      selectedKey={generateStateValueProp($state, [
        "ariaSelect",
        "selectedValue"
      ])}
    >
      {$props.showLabel ? (
        <Label2
          data-plasmic-name={"label2"}
          data-plasmic-override={overrides.label2}
          className={classNames("__wab_instance", sty.label2)}
        >
          {renderPlasmicSlot({
            defaultContents: "Label",
            value: args.label
          })}
        </Label2>
      ) : null}
      <BaseButton
        data-plasmic-name={"ariaButton"}
        data-plasmic-override={overrides.ariaButton}
        className={classNames("__wab_instance", sty.ariaButton, {
          [sty.ariaButtontype_soft]: hasVariant($state, "type", "soft")
        })}
      >
        <BaseSelectValue
          data-plasmic-name={"ariaSelectedValue"}
          data-plasmic-override={overrides.ariaSelectedValue}
          className={classNames("__wab_instance", sty.ariaSelectedValue)}
          customize={true}
        >
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.placeholder;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "Select an item";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </BaseSelectValue>
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <ChevronDownIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg)}
            role={"img"}
          />
        </div>
      </BaseButton>
      {$props.showDescription ? (
        <Description2
          data-plasmic-name={"description2"}
          data-plasmic-override={overrides.description2}
          className={classNames("__wab_instance", sty.description2)}
        >
          {renderPlasmicSlot({
            defaultContents: "Description...",
            value: args.description
          })}
        </Description2>
      ) : null}
      <MenuPopover2
        data-plasmic-name={"menuPopover2"}
        data-plasmic-override={overrides.menuPopover2}
        className={classNames("__wab_instance", sty.menuPopover2)}
        menuItems={renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <MenuItem2 label={"Item 1"} value={"item1"} />
              <MenuItem2 label={"Item 2"} value={"item2"} />
              <MenuItem2 label={"Item 3"} value={"item3"} />
              <MenuSection2
                className={classNames("__wab_instance", sty.menuSection2__b0DT)}
                header={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yp1Cj
                    )}
                  >
                    {"Section"}
                  </div>
                }
                items={
                  <React.Fragment>
                    <MenuItem2
                      label={"Section Item 1"}
                      value={"section-item-1"}
                    />

                    <MenuItem2
                      label={"Section Item 2"}
                      value={"section-item-2"}
                    />

                    <MenuItem2
                      label={"Section Item 3"}
                      value={"section-item-3"}
                    />
                  </React.Fragment>
                }
              />
            </React.Fragment>
          ),

          value: args.items
        })}
        offset={2}
      />
    </BaseSelect>
  );
}

const PlasmicDescendants = {
  ariaSelect: [
    "ariaSelect",
    "label2",
    "ariaButton",
    "ariaSelectedValue",
    "text",
    "freeBox",
    "svg",
    "description2",
    "menuPopover2"
  ],

  label2: ["label2"],
  ariaButton: ["ariaButton", "ariaSelectedValue", "text", "freeBox", "svg"],
  ariaSelectedValue: ["ariaSelectedValue", "text"],
  text: ["text"],
  freeBox: ["freeBox", "svg"],
  svg: ["svg"],
  description2: ["description2"],
  menuPopover2: ["menuPopover2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSelect2__ArgProps,
          internalVariantPropNames: PlasmicSelect2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSelect2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaSelect") {
    func.displayName = "PlasmicSelect2";
  } else {
    func.displayName = `PlasmicSelect2.${nodeName}`;
  }
  return func;
}

export const PlasmicSelect2 = Object.assign(
  // Top-level PlasmicSelect2 renders the root element
  makeNodeComponent("ariaSelect"),
  {
    // Helper components rendering sub-elements
    label2: makeNodeComponent("label2"),
    ariaButton: makeNodeComponent("ariaButton"),
    ariaSelectedValue: makeNodeComponent("ariaSelectedValue"),
    text: makeNodeComponent("text"),
    freeBox: makeNodeComponent("freeBox"),
    svg: makeNodeComponent("svg"),
    description2: makeNodeComponent("description2"),
    menuPopover2: makeNodeComponent("menuPopover2"),
    // Metadata about props expected for PlasmicSelect2
    internalVariantProps: PlasmicSelect2__VariantProps,
    internalArgProps: PlasmicSelect2__ArgProps
  }
);

export default PlasmicSelect2;
/* prettier-ignore-end */
