/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZ8YLJfMu4Bkb27adUM6r5
// Component: uE-nokRAoK9M
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import SiteHeader from "../../SiteHeader"; // plasmic-import: N2EmXWwtxdPX/component
import { HeroTopography } from "../../HeroTopography"; // plasmic-import: jiWrq2otqjSL/codeComponent
import { ParticleHero } from "../../ParticleHero"; // plasmic-import: DaOFkwlQNp2H/codeComponent
import { ImageReveal } from "../../ImageReveal"; // plasmic-import: y9GA8gOL7hbN/codeComponent
import { AboutHorizontal2 } from "../../AboutHorizontal2"; // plasmic-import: ly7oXzZR4mDW/codeComponent
import SkillsSection from "../../SkillsSection"; // plasmic-import: fwQPOdwx7HmF/component
import AiSys from "../../AiSys"; // plasmic-import: XaX9xed_u-2k/component
import { ContactFormCard } from "../../ContactFormCard"; // plasmic-import: 2LKy0tK2Wju8/codeComponent
import SiteFooter from "../../SiteFooter"; // plasmic-import: cswDm0qYBFlc/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: vZ8YLJfMu4Bkb27adUM6r5/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: uE-nokRAoK9M/css
import versyTriangle7HCvmehTD3Y from "./images/versyTriangle.svg"; // plasmic-import: 7hCVMEH-tD3y/picture
import versylogoWebpAnUVLpSztBa from "./images/versylogoWebp.webp"; // plasmic-import: anU_vLpSztBA/picture
import myBeppeWgjwaozifOlk from "./images/myBeppe.png"; // plasmic-import: wgjwaozifOlk/picture

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    title: "Claudio Palana - Home",
    openGraph: {
      title: "Claudio Palana - Home"
    },
    twitter: {
      card: "summary",
      title: "Claudio Palana - Home"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"homepage"}
          data-plasmic-override={overrides.homepage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.homepage
          )}
        >
          <SiteHeader
            data-plasmic-name={"siteHeader"}
            data-plasmic-override={overrides.siteHeader}
            className={classNames("__wab_instance", sty.siteHeader)}
          />

          <section
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <HeroTopography
              data-plasmic-name={"heroTopography"}
              data-plasmic-override={overrides.heroTopography}
              className={classNames("__wab_instance", sty.heroTopography)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__napsj)}>
              <ParticleHero
                data-plasmic-name={"particleHero"}
                data-plasmic-override={overrides.particleHero}
                className={classNames("__wab_instance", sty.particleHero)}
              />

              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__gIwWd
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Architect of Experience\nProduct Shaper\nSignal Crafter"
                  : "Architect of Experience \u00b7 Product Shaper \u00b7 Signal Crafter"}
              </h1>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__q6WJc
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Designing complex systems that teams can trust, use, and evolve. Turning complexity into tools people can actually lead with."
                  : "Designing complex systems that teams can trust, use, and evolve. Turning complexity into tools people can actually lead with."}
              </h1>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7XvAn
              )}
            >
              {"SCROLL TO EXPLORE \u2193"}
            </div>
          </section>
          <section
            data-plasmic-name={"projects"}
            data-plasmic-override={overrides.projects}
            className={classNames(projectcss.all, sty.projects)}
            id={"Projects"}
          >
            <section
              data-plasmic-name={"versy"}
              data-plasmic-override={overrides.versy}
              className={classNames(projectcss.all, sty.versy)}
              data-bg-src={"/projects/beppe-bg.jpg"}
              data-mockup-src={"/projects/beppe-mock.png"}
              data-project-id={"my-beppe-1"}
              onClick={async event => {
                const $steps = {};
                $steps["goToMyBeppe"] = true
                  ? (() => {
                      const actionArgs = { destination: `/projects/my-beppe` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          location.assign(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToMyBeppe"] != null &&
                  typeof $steps["goToMyBeppe"] === "object" &&
                  typeof $steps["goToMyBeppe"].then === "function"
                ) {
                  $steps["goToMyBeppe"] = await $steps["goToMyBeppe"];
                }
              }}
              title={"Testo"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___2IQgt)}
                displayHeight={"235px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"33%"}
                loading={"lazy"}
                src={{
                  src: versyTriangle7HCvmehTD3Y,
                  fullWidth: 167,
                  fullHeight: 146,
                  aspectRatio: undefined
                }}
              />

              <div className={classNames(projectcss.all, sty.freeBox__gf9Gk)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___3INsk)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__dFmP0)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: versylogoWebpAnUVLpSztBa,
                      fullWidth: 1134,
                      fullHeight: 454,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y3ZxS
                  )}
                >
                  {
                    "Branding \u00b7 Design System \u00b7 Visual Direction \u00b7 Product Support"
                  }
                </div>
                <div
                  data-plasmic-name={"details16"}
                  data-plasmic-override={overrides.details16}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.details16
                  )}
                  data-project-details={"1"}
                >
                  {
                    "MyBeppe is not just a food delivery app.\nIt\u2019s a digital translation of a local market experience.\n\nA product where UX, branding, and storytelling work together to build trust \u2014 one interaction at a time."
                  }
                </div>
              </div>
            </section>
            <section
              data-plasmic-name={"myBeppe"}
              data-plasmic-override={overrides.myBeppe}
              className={classNames(projectcss.all, sty.myBeppe)}
              data-bg-src={"/projects/beppe-bg.jpg"}
              data-mockup-src={"/projects/beppe-mock.png"}
              data-project-id={"my-beppe-1"}
              onClick={async event => {
                const $steps = {};
                $steps["goToMyBeppe"] = true
                  ? (() => {
                      const actionArgs = { destination: `/projects/my-beppe` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          location.assign(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToMyBeppe"] != null &&
                  typeof $steps["goToMyBeppe"] === "object" &&
                  typeof $steps["goToMyBeppe"].then === "function"
                ) {
                  $steps["goToMyBeppe"] = await $steps["goToMyBeppe"];
                }
              }}
              title={"Testo"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__wqkHe)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"33%"}
                loading={"lazy"}
                src={{
                  src: myBeppeWgjwaozifOlk,
                  fullWidth: 1536,
                  fullHeight: 1024,
                  aspectRatio: undefined
                }}
              />

              <div className={classNames(projectcss.all, sty.freeBox__fL3T4)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e2TtT
                  )}
                >
                  {"MyBeppe"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l8YYd
                  )}
                >
                  {
                    "Case Study \u00b7 UI Design \u00b7 UX Research \u00b7 Visual Identity"
                  }
                </div>
                <div
                  data-plasmic-name={"details17"}
                  data-plasmic-override={overrides.details17}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.details17
                  )}
                  data-project-details={"1"}
                >
                  {
                    "MyBeppe is not just a food delivery app.\nIt\u2019s a digital translation of a local market experience.\n\nA product where UX, branding, and storytelling work together to build trust \u2014 one interaction at a time."
                  }
                </div>
              </div>
            </section>
            <ImageReveal
              data-plasmic-name={"imageReveal"}
              data-plasmic-override={overrides.imageReveal}
              className={classNames("__wab_instance", sty.imageReveal)}
            />
          </section>
          <section
            data-plasmic-name={"about"}
            data-plasmic-override={overrides.about}
            className={classNames(projectcss.all, sty.about)}
            id={"About"}
          >
            <AboutHorizontal2
              data-plasmic-name={"aboutHorizontal2"}
              data-plasmic-override={overrides.aboutHorizontal2}
              className={classNames("__wab_instance", sty.aboutHorizontal2)}
            />
          </section>
          <SkillsSection
            data-plasmic-name={"skillsSection"}
            data-plasmic-override={overrides.skillsSection}
            className={classNames("__wab_instance", sty.skillsSection)}
          />

          <AiSys
            data-plasmic-name={"aiSys"}
            data-plasmic-override={overrides.aiSys}
            className={classNames("__wab_instance", sty.aiSys)}
          />

          <section
            data-plasmic-name={"contact"}
            data-plasmic-override={overrides.contact}
            className={classNames(projectcss.all, sty.contact)}
            id={"Contact"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kEoi8
              )}
            >
              {"CONTACT"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__qIoUx)}>
              <ContactFormCard
                data-plasmic-name={"contactFormCard"}
                data-plasmic-override={overrides.contactFormCard}
                className={classNames("__wab_instance", sty.contactFormCard)}
              />
            </div>
          </section>
          <SiteFooter
            data-plasmic-name={"siteFooter"}
            data-plasmic-override={overrides.siteFooter}
            className={classNames("__wab_instance", sty.siteFooter)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  homepage: [
    "homepage",
    "siteHeader",
    "hero",
    "heroTopography",
    "particleHero",
    "projects",
    "versy",
    "details16",
    "myBeppe",
    "details17",
    "imageReveal",
    "about",
    "aboutHorizontal2",
    "skillsSection",
    "aiSys",
    "contact",
    "contactFormCard",
    "siteFooter"
  ],

  siteHeader: ["siteHeader"],
  hero: ["hero", "heroTopography", "particleHero"],
  heroTopography: ["heroTopography"],
  particleHero: ["particleHero"],
  projects: [
    "projects",
    "versy",
    "details16",
    "myBeppe",
    "details17",
    "imageReveal"
  ],

  versy: ["versy", "details16"],
  details16: ["details16"],
  myBeppe: ["myBeppe", "details17"],
  details17: ["details17"],
  imageReveal: ["imageReveal"],
  about: ["about", "aboutHorizontal2"],
  aboutHorizontal2: ["aboutHorizontal2"],
  skillsSection: ["skillsSection"],
  aiSys: ["aiSys"],
  contact: ["contact", "contactFormCard"],
  contactFormCard: ["contactFormCard"],
  siteFooter: ["siteFooter"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "homepage") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("homepage"),
  {
    // Helper components rendering sub-elements
    siteHeader: makeNodeComponent("siteHeader"),
    hero: makeNodeComponent("hero"),
    heroTopography: makeNodeComponent("heroTopography"),
    particleHero: makeNodeComponent("particleHero"),
    projects: makeNodeComponent("projects"),
    versy: makeNodeComponent("versy"),
    details16: makeNodeComponent("details16"),
    myBeppe: makeNodeComponent("myBeppe"),
    details17: makeNodeComponent("details17"),
    imageReveal: makeNodeComponent("imageReveal"),
    about: makeNodeComponent("about"),
    aboutHorizontal2: makeNodeComponent("aboutHorizontal2"),
    skillsSection: makeNodeComponent("skillsSection"),
    aiSys: makeNodeComponent("aiSys"),
    contact: makeNodeComponent("contact"),
    contactFormCard: makeNodeComponent("contactFormCard"),
    siteFooter: makeNodeComponent("siteFooter"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
